name: Build Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      working-directory: ./client
      run: bun install

    - name: Build production bundle
      working-directory: ./client
      run: bun run build

    - name: Upload dist folder artifact
      uses: actions/upload-artifact@v4
      with:
        name: production-dist
        path: client/dist/
